### ISSUE TITLE
Wikitablescrape

### ISSUE THREAD

**Issue by ashar0706** [rocheio/wiki-table-scrape#4]
When I am trying to import wikitablescrape it gives an error. how to fix it?

**Comment by rocheio** [comment]
Hi @ashar0706,

Since this was more of an academic project than something production-ready, I have not hosted this on PyPI or made a proper `setup.py` file so that you can just install via pip.

If you clone the repo and then follow the install steps you should be able to get it to work, and then you can do whatever you want with the file from there. Here's a basic proof of concept:

```
andy@andy-mbp git $ git clone git@github.com:rocheio/wiki-table-scrape.git
...
andy@andy-mbp git $ cd wiki-table-scrape/
andy@andy-mbp wiki-table-scrape (master)$ python3 -m venv venv
andy@andy-mbp wiki-table-scrape (master)$ . venv/bin/activate
(venv) andy@andy-mbp wiki-table-scrape (master)$ pip install -r requirements.txt
...
(venv) andy@andy-mbp wiki-table-scrape (master)$ python -c 'import wikitablescrape; print(wikitablescrape)'
<module 'wikitablescrape' from '/Users/andy/git/wiki-table-scrape/wikitablescrape.py'>
``` 

Please let me know what errors you are receiving / at what step and I can try to help further.
