### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by temikelani** [rocheio/wiki-table-scrape#8]
some tables have titles that are too long and you get the error above

for example
link: https: //en.wikipedia.org/wiki/Super_Bowl_television_ratings
Table title: List of Super Bowl television ratings in the United States with average viewers, total viewers, average households, household rating and share,18–49 rating and share and average cost of 30-second ad, showing the period they were measured between, Super Bowl, date and network aired on

**Comment by rocheio** [comment]
Thanks for letting me know! I just fixed this with https://github.com/rocheio/wiki-table-scrape/commit/86796c7373bc280d509513bcae86354e18bd95da and it should work now using `pip install wikitablescrape==1.0.4`. I chose a default max of 250 since that seems to be the standard for most major OS, but you can override that value with an environment variable if you want.

Please re-open or create a new issue if you have any other problems!
